fun main() {
//    println("${solution.SolutionDay01()}")
//    println("${solution.SolutionDay02()}")
//    println("${solution.SolutionDay03()}")
//    println("${solution.SolutionDay04()}")
//    println("${solution.SolutionDay05()}")
//    println("${solution.SolutionDay06()}")
//    println("${solution.SolutionDay07()}")
//    println("${solution.SolutionDay08()}")
//    println("${solution.SolutionDay09()}")
//    println("${solution.SolutionDay10()}")
//    println("${solution.SolutionDay11()}")
//    println("${solution.SolutionDay12()}")
//    println("${solution.SolutionDay13()}")
 //   println("${solution.SolutionDay14()}")
    //println("${solution.SolutionDay15()}")
    // println("${solution.SolutionDay16()}")
    //println("${solution.SolutionDay17()}")
    //println("${solution.SolutionDay18()}")
    //println("${solution.SolutionDay19()}")
    //println("${solution.SolutionDay20()}")
    //println("${solution.SolutionDay21()}")
    //println("${solution.SolutionDay22()}")
    //println("${solution.SolutionDay23()}")
    println("${solution.SolutionDay24()}")
}